version: '3.7'

services:

  web:
    build: .
    command: gunicorn djangoWeather.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=
      - DEBUG=0
      - ENVIRONMENT=production
      - POSTGRES_NAME=
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=
      - POSTGRES_PORT=
      - OPEN_WEATHER_TOKEN=

    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
     - db

  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - postgres_weather:/var/lib/postgresql/data/


volumes:
  postgres_weather: